### ISSUE TITLE
DsKeyToCid is out of place

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-ds-help#24]
We explicitly switched away from making `CidToDsKey`/`DsKeyToCid` convert to/from multihashes under the hood, introducing `MultihashToDsKey`/`DsKeyToMultihash`. However, we now have a `DsKeyToCidV1` function that _does_ convert under the hood. This seems  inconsistent.

**Comment by hsanjuan** [comment]
We switched away to prevent silent breakage not because they were not useful.

Was it too radical to introduce a helper to parse the multihashes to CidV1 directly? Having to provide the CID type means it cannot be used as drop-in replacement. Docstring also mentions that the given key should be a raw multihash.

If you want it removed just say, I simply did not expect it would be an issue.

**Comment by Stebalien** [comment]
Ah, ok. I thought your primary concern was the implicit conversion. I have no problem with them, I was just confused.
